[phases.build]
cmds = [
  "sbt cascadeJS/fullLinkJS",
  "sbt cascadeJVM/stage",
  "mkdir -p target/universal",
  "cp -r jvm/target/universal/stage target/universal/"
]

[start]
cmd = "./target/universal/stage/bin/main"

